import fs from "node:fs";
import path from "node:path";

const ROOT = "D:/canvasbrick-demo";
const DIR = path.join(ROOT, "public/assets/portfolio");

const list = (slug) => {
  const p = path.join(DIR, slug);
  if (!fs.existsSync(p)) return [];
  return fs.readdirSync(p)
    .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
    .sort()
    .map((f) => `/assets/portfolio/${slug}/${f}`);
};

// folder-backed categories
const folder = {
  mandir: list("mandir"),
  living: list("living"),
  kitchen: list("kitchen"),
  bedroom: list("bedroom"),
  wardrobe: list("wardrobe"),
  tvunit: list("tvunit"),
  crockery: list("crockery"),
  console: list("console"),
};

// derived from existing cinematic photo set (no dedicated folders)
const cin = (f) => `/assets/cinematic/${f}`;
const derived = {
  balcony: [cin("balcony-pool.jpg"), cin("terrace-night.jpg"), cin("atrium.jpg"), cin("living-square.jpg")],
  foyers: [cin("foyer-mirror.jpg"), cin("buddha-foyer.jpg"), cin("jali-partition.jpg"), cin("marble-console.jpg")],
};

const V = (f) => `/assets/portfolio/videos/${f}`;

// category metadata, in portfolio display order
const meta = [
  { slug:"mandir",   id:"pujamandir", title:"Pooja & Mandir", tag:"Sacred corners",
    headline:"A Pooja Room For The Soul", subtitle:"Where faith meets craft",
    blurb:"Carved jali, marble and warm brass — quiet corners for prayer, designed with vastu in mind and built to be handed down.",
    video:V("video3_1767961591.mp4") },
  { slug:"living",   id:"living", title:"Living Rooms", tag:"Where the home gathers",
    headline:"Where The Home Comes Together", subtitle:"Living, beautifully",
    blurb:"Layered lighting, honest materials and seating that pulls a family together — living rooms designed around how you actually live.",
    video:V("catalogue-tab-1.mp4") },
  { slug:"kitchen",  id:"kitchen", title:"Modular Kitchens", tag:"Built for real cooking",
    headline:"Kitchens Built For Real Life", subtitle:"Where the day begins",
    blurb:"Manufactured in-house to millimetre tolerances. Stone, hardware and finishes chosen for daily Indian cooking, for decades.",
    video:V("catalogue-tab-2.mp4") },
  { slug:"bedroom",  id:"bedroom", title:"Bedrooms", tag:"The quiet rooms",
    headline:"Bedrooms That Let You Exhale", subtitle:"Rest, redesigned",
    blurb:"Warm veneers, soft light and storage that disappears — bedrooms that feel calm the moment you walk in.",
    video:V("catalogue-tab-3.mp4") },
  { slug:"wardrobe", id:"wardrobe", title:"Wardrobes", tag:"Storage, considered",
    headline:"A Place For Everything", subtitle:"Wardrobes, engineered",
    blurb:"Sliding, hinged and walk-in — wardrobes engineered around your things, finished the way our family has for fifty years.",
    video:V("catalogue-tab-4.mp4") },
  { slug:"tvunit",   id:"tvunit", title:"TV Units", tag:"The wall that anchors the room",
    headline:"The Wall Everyone Gathers Around", subtitle:"Media, made beautiful",
    blurb:"Fluted panels, floating consoles and hidden cable runs — media walls that look built-in because they are.",
    video:V("catalogue-tab-5.mp4") },
  { slug:"crockery", id:"crockery", title:"Crockery Units", tag:"Everyday, elevated",
    headline:"For The Pieces Worth Showing", subtitle:"Everyday, elevated",
    blurb:"Glass, brass and seasoned wood — display and storage for the pieces a family brings out for guests and keeps for good." },
  { slug:"console",  id:"console", title:"Console Units", tag:"First impressions",
    headline:"The First Hello Of A Home", subtitle:"First impressions, framed",
    blurb:"Slim consoles and entryway pieces that set the tone the moment a door opens." },
  { slug:"balcony",  id:"balcony", title:"Outdoor & Balcony", tag:"Rooms without a roof",
    headline:"Outdoors & Balcony", subtitle:"Tailored for you",
    blurb:"Decks, terraces and pool-side lounges — outdoor spaces detailed to weather Bengal's seasons and still feel like the studio." },
  { slug:"foyers",   id:"foyers", title:"Foyers", tag:"The threshold",
    headline:"The Threshold That Sets The Tone", subtitle:"Enter in style",
    blurb:"Jali screens, mirrors and layered brass — entrance foyers that introduce a home before you've fully stepped inside." },
];

const cats = meta.map((m) => {
  const images = folder[m.slug] ?? derived[m.slug] ?? [];
  return { ...m, images };
});

const header = `// AUTO-GENERATED by scripts/gen-gallery.mjs — edit metadata there, not here.
// Local media copied from D:\\canvasbrickdemoimages into public/assets/portfolio.

export type GalleryCategory = {
  slug: string;
  /** anchor id on /portfolio */
  id: string;
  title: string;
  tag: string;
  /** poetic KariGhars-style centered headline */
  headline: string;
  /** short line under the headline */
  subtitle: string;
  blurb: string;
  video?: string;
  images: string[];
};

export const galleryCategories: GalleryCategory[] = ${JSON.stringify(cats, null, 2)};

export const galleryBySlug = Object.fromEntries(
  galleryCategories.map((c) => [c.slug, c]),
) as Record<string, GalleryCategory>;

/** link to a category's section on the portfolio page */
export const portfolioHref = (id: string) => \`/portfolio#\${id}\`;
`;

fs.writeFileSync(path.join(ROOT, "lib/gallery.ts"), header);
console.log("wrote lib/gallery.ts");
cats.forEach((c) => console.log(`  ${c.slug} (#${c.id}): ${c.images.length} imgs${c.video ? " +video" : ""}`));
